### ISSUE TITLE
Error  Link 2019 unresolved external symbol

### ISSUE THREAD

**Issue by BroOfBros** [whoshuu/cpr#182]
I cant compile my project in VS2015

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __cdecl cpr::Session::~Session(void)" (??1Session@cpr@@QEAA@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@cpr@@YA?AVResponse@0@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	TestingQT	C:\Users\Cata\Desktop\TestingQT\TestingQT\TestingQT\testingqt.obj	1

**Comment by zxvnme** [comment]
I have same issue.

![obraz](https://user-images.githubusercontent.com/25554893/35696009-6a6d9548-0786-11e8-8849-ee0dbf80a58f.png)

**Comment by COM8** [comment]
Should be fixed in #378.
Feel free to reopen if not.

**Comment by whyCPPgofast** [comment]
@BroOfBros , @zxvnme have you guys found a workaround for this problem?

**Comment by Kid0h** [comment]
ping @KingKili 
This problem still exists..

I even tried building and adding the cpr.lib as an input and it still happens, is this bug even getting any attention?
**Important note:** When using CPR from VCPKG it works fine **only** when not set to use Static Libraries (if set to use Static Libraries, you get more than 100 unresolved externals),
when using CPR from the source code's include folder, you get those 4 unresolved externals (whether you add the cpr.lib as a dependency or not).

It's like this project isn't even meant to be used as static library, you have to have those `libcurl.dll` and `zlib1.dll` right next to the binary for it to work..
Oldest version of this bug exiting that I could find was released around 7 months ago.

**Comment by KingKili** [comment]
Are still shared libraries built, if you not use VCPK and set `-DBUILD_SHARED_LIBS=OFF` as parameter for the CMake run?

**Comment by Kid0h** [comment]
I tried now building the cpr.lib with the `-DBUILD_SHARED_LIBS=OFF` parameter, and this error still occurs. 
![image](https://user-images.githubusercontent.com/49398015/105716513-9ac69180-5f27-11eb-9aa1-d034fe547ac8.png)

**Comment by KingKili** [comment]
But did it build dll files?

**Comment by Kid0h** [comment]
No it did not.
The only way I can actually build the binary is with using the CPR from VCPKG, and with that CPR I cannot build it as a static library, so it only works with the DLLs.
